spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/brewing-buddy
    username: compose-postgres
    password: compose-postgres
    driverClassName: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: PostgreSQLDialect
  sql:
    init:
      mode: always
  mvc:
    throw-exception-if-no-handler-found: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html